version: '3.8'
services:
  core_node:
    image: pallavi/nodeapp:latest
    deploy:
      replicas: 2
    networks:
      - app-net

  redis-master:
    image: redis:latest
    networks:
      - app-net

  mongo1:
    image: mongo:latest
    networks:
      - app-net

  nginx:
    image: nginx:latest
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - app-net

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    networks:
      - monitoring-net

  node-exporter:
    image: prom/node-exporter
    deploy:
      mode: global
    networks:
      - monitoring-net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    deploy:
      mode: global
    networks:
      - monitoring-net

  mongo-exporter:
    image: percona/mongodb_exporter:0.40.0
    environment:
      MONGODB_URI: mongodb://mongo1:27017
    ports:
      - "9217:9216"
    networks:
      - monitoring-net

  redis-exporter:
    image: oliver006/redis_exporter
    command: ["--redis.addr=redis://redis-master:6379"]
    ports:
      - "9122:9121"
    networks:
      - monitoring-net

networks:
  app-net:
  monitoring-net:
